# 안녕하세요^^ 
## AIVLE 미니프로젝트 '서울시 생활정보 기반 대중교통 수요 분석 ' 과정에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

## 개인과제
* 데이터 구조, 분포 확인, 전처리 : 1.1_버스정류장데이터 / 1.2 유동인구데이터 / 1.3_주민등록데이터 / 1.4_업종등록데이터
* 데이터간 관계 가설 수립 및 검증 : 1.5_데이터 분석

---

# 데이터 분석부터 먼저 시작해보겠습니다.
## "구별 업종 등록 데이터" 를 확인해 보도록 하겠습니다

In [1]:
# 필요 라이브러리부터 설치합니다.
%pip install pandas seaborn

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: seaborn in c:\users\user\anaconda3\lib\site-packages (0.11.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: scipy>=1.0 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.9.1)
Requirement already satisfied: matplotlib>=2.2 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (3.5.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.9)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from matplotlib>=2.2->seaborn) (22.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

## 기본전제
* 처음에 제공되는 기본/추가 데이터는 'raw_data' 폴더에 있습니다.

[기본 데이터]
* business_type.csv

[데이터 소개]
* 서울 시 구별 등록 업종 상위 10개 데이터
    * 택시운송업
    * 한식일반음식점업
    * 용달 화물자동차 운송업
    * 부동산 중개 및 대리업
    * 두발미용업
    * 커피전문점
    * 남녀용 겉옷 및 셔츠 도매업
    * 기타주점업
    * 일반 교과 학원
    * 한식 육류요리 전문점

[변수 소개]
* 다수 업종 상위 1~10

---

# 1.데이터 불러오기
## 모든 미니 프로젝트의 시작은 '데이터 불러오기' 부터라고 할 수 있습니다.
+ KeyPoint : 불러오고자 하는 데이터에 따라 자유롭게 변수로 지정할 수 있다.

###  데이터 프레임을 불러오고 변수로 저장(여기서는 CSV 기준으로 진행)
* csv : pd.read_csv("파일이름. csv")
* txt : pd.read_csv("파일이름. csv", sep="구분자")
* xlsx : pd.read_excel('파일이름.xlsx')
* pickle : pd.read_pickle("파일이름.pkl") <br>
 [참고] pickle은 파이썬의 모든 객체를 파일로 저장할 수 있는 방법으로 DataFrame,List,Dict 등 모든 객체 저장 가능(특히 sklearn라이브러리를 통해 모델을 학습시키고, 저장할 때 많이 사용)

## 기본전제
* 처음에 제공되는 데이터는 'raw_data' 폴더에 있습니다.

[기본 데이터]
* 1.4 business_type.csv

[데이터 소개]
* 서울시 업종 등록 데이터

#### [실습문제1] 데이터 로딩
* '1.4 business_type.csv'파일을 'seoul_business' 변수에 저장하고 그 데이터를 확인하세요.
    * 데이터 파일 로딩시 참고 사항 
        * 구분자(sep)는 ',' 입니다
        * UTF-8 인코더를 사용해 주세요

In [2]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
import pandas as pd
seoul_business=pd.read_csv("1.4 business_type.csv",sep=",",encoding="UTF-8",thousands = ',',header=1)
seoul_business

,자치구,동,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
0,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
1,합계,합계,"47,176","76,701","29,225","100,183","28,494","29,356","24,013","42,636",...,"16,255","57,322","13,388","51,116","13,339","31,371","11,911","50,773","11,109","44,653"
2,종로구,소계,215,215,"1,548","5,912",618,646,549,889,...,948,"3,613",400,962,537,"1,413",110,382,437,"1,982"
3,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220
4,종로구,삼청동,5,5,42,145,4,4,9,10,...,66,243,2,3,3,8,-,-,7,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,강동구,성내3동,120,120,135,390,73,73,104,163,...,54,133,10,86,57,103,66,199,44,164
446,강동구,둔촌2동,117,436,63,249,89,89,61,108,...,34,85,10,788,21,39,35,90,24,101
447,강동구,암사1동,209,372,71,195,153,153,67,107,...,29,59,3,6,47,98,31,67,34,98
448,강동구,천호2동,157,187,152,509,144,151,97,188,...,63,212,4,17,95,268,24,42,69,245
449,강동구,길동,"1,441","1,557",152,436,217,225,146,237,...,71,228,6,126,122,294,39,136,70,224

In [27]:
# 데이터 프레임의 Shape을 확인합니다.
seoul_business.shape

(451, 22)

In [28]:
# seoul_business.loc[seoul_business["자치구"]=="강동구"]

,자치구,동,다수업종 상위10,다수업종 상위10.1,다수업종 상위10.2,다수업종 상위10.3,다수업종 상위10.4,다수업종 상위10.5,다수업종 상위10.6,다수업종 상위10.7,...,다수업종 상위10.10,다수업종 상위10.11,다수업종 상위10.12,다수업종 상위10.13,다수업종 상위10.14,다수업종 상위10.15,다수업종 상위10.16,다수업종 상위10.17,다수업종 상위10.18,다수업종 상위10.19
433,강동구,소계,"3,295","4,980","1,101","3,388","1,528","1,566","1,188","1,990",...,546,"1,660",59,"1,433",589,"1,349",620,"2,104",428,"1,459"
434,강동구,강일동,183,543,20,85,121,124,29,48,...,12,63,1,3,1,2,37,109,6,19
435,강동구,상일동,99,99,41,112,95,95,62,110,...,15,38,-,-,14,30,14,34,20,52
436,강동구,명일1동,119,119,56,167,61,65,59,88,...,45,125,2,32,36,85,51,259,27,90
437,강동구,명일2동,2,2,27,120,11,11,37,60,...,22,100,4,10,4,11,159,610,13,45
438,강동구,고덕1동,102,102,21,53,52,62,59,94,...,15,32,-,-,12,20,23,51,6,19
439,강동구,고덕2동,52,52,36,90,59,59,141,280,...,8,26,-,-,7,11,3,8,3,12
440,강동구,암사2동,106,369,31,106,59,59,38,52,...,15,36,1,5,10,23,28,83,14,54
441,강동구,암사3동,73,73,9,23,40,40,24,42,...,11,47,-,-,4,7,38,148,4,11
442,강동구,천호1동,185,293,55,160,132,132,51,70,...,22,58,2,5,26,43,24,110,19,66
443,강동구,천호3동,137,278,71,203,84,84,78,125,...,32,123,6,70,56,148,11,43,27,83
444,강동구,성내1동,105,105,85,283,54,60,48,74,...,58,194,8,282,29,65,23,86,18,62
445,강동구,성내2동,88,273,76,207,84,84,87,144,...,40,101,2,3,48,102,14,29,30,114
446,강동구,성내3동,120,120,135,390,73,73,104,163,...,54,133,10,86,57,103,66,199,44,164
447,강동구,둔촌2동,117,436,63,249,89,89,61,108,...,34,85,10,788,21,39,35,90,24,101
448,강동구,암사1동,209,372,71,195,153,153,67,107,...,29,59,3,6,47,98,31,67,34,98
449,강동구,천호2동,157,187,152,509,144,151,97,188,...,63,212,4,17,95,268,24,42,69,245
450,강동구,길동,"1,441","1,557",152,436,217,225,146,237,...,71,228,6,126,122,294,39,136,70,224

---

# 2.기본 정보 확인 및 클렌징

+ 데이터 클렌징 : 결측치, 이상치 등을 제거하여 데이터 분석 결과가 왜곡 되는 문제를 방지하기 위한 정제 과정

#### [실습문제2] 기본 정보 확인하기
* 'seoul_moving' 데이터의 정보를 확인해보세요.
* 'describe', 'info', 'head' 등 전부 활용해 보겠습니다.

In [29]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

seoul_business.describe()

,자치구,동,다수업종 상위10,다수업종 상위10.1,다수업종 상위10.2,다수업종 상위10.3,다수업종 상위10.4,다수업종 상위10.5,다수업종 상위10.6,다수업종 상위10.7,...,다수업종 상위10.10,다수업종 상위10.11,다수업종 상위10.12,다수업종 상위10.13,다수업종 상위10.14,다수업종 상위10.15,다수업종 상위10.16,다수업종 상위10.17,다수업종 상위10.18,다수업종 상위10.19
count,451,451,451,451,451,451,451,451,451,451,...,451,451,451,451,451,451,451,451,451,451
unique,27,425,226,280,176,305,177,180,142,205,...,131,239,69,147,127,189,113,222,107,230
top,송파구,소계,71,11,24,104,56,56,40,54,...,13,16,-,-,18,20,4,42,17,45
freq,28,25,7,7,11,6,8,9,11,9,...,18,8,82,82,14,10,15,10,16,9

In [30]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business.head()

,자치구,동,다수업종 상위10,다수업종 상위10.1,다수업종 상위10.2,다수업종 상위10.3,다수업종 상위10.4,다수업종 상위10.5,다수업종 상위10.6,다수업종 상위10.7,...,다수업종 상위10.10,다수업종 상위10.11,다수업종 상위10.12,다수업종 상위10.13,다수업종 상위10.14,다수업종 상위10.15,다수업종 상위10.16,다수업종 상위10.17,다수업종 상위10.18,다수업종 상위10.19
0,자치구,동,택시운송업,택시운송업,한식 일반 음식점업,한식 일반 음식점업,용달 화물자동차 운송업,용달 화물자동차 운송업,부동산 중개 및 대리업,부동산 중개 및 대리업,...,커피전문점,커피전문점,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업,기타주점업,기타주점업,일반 교과 학원,일반 교과 학원,한식 육류요리 전문점,한식 육류요리 전문점
1,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
2,합계,합계,"47,176","76,701","29,225","100,183","28,494","29,356","24,013","42,636",...,"16,255","57,322","13,388","51,116","13,339","31,371","11,911","50,773","11,109","44,653"
3,종로구,소계,215,215,"1,548","5,912",618,646,549,889,...,948,"3,613",400,962,537,"1,413",110,382,437,"1,982"
4,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220

#### [실습문제3] 데이터 확인 및 처리

* 데이터를 보았을때, 어느 데이터를 가져와야 할지 생각 해 봅시다.

In [3]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
a=seoul_business.loc[seoul_business["동"]=='소계']
a=a.drop("동",axis=1)
a.set_index('자치구',inplace=True)
for i in a.columns:
    y=a[i].values
    u=[]
    for j in y:
        j=int(j.replace(",",""))
        u.append(j)
    a[i]=u
# a.astype('int')   
a.reset_index(inplace=True)
a.info()
a

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   자치구                25 non-null     object
 1   택시운송업              25 non-null     int64
 2   택시운송업.1            25 non-null     int64
 3   한식 일반 음식점업         25 non-null     int64
 4   한식 일반 음식점업.1       25 non-null     int64
 5   용달 화물자동차 운송업       25 non-null     int64
 6   용달 화물자동차 운송업.1     25 non-null     int64
 7   부동산 중개 및 대리업       25 non-null     int64
 8   부동산 중개 및 대리업.1     25 non-null     int64
 9   두발미용업              25 non-null     int64
 10  두발미용업.1            25 non-null     int64
 11  커피전문점              25 non-null     int64
 12  커피전문점.1            25 non-null     int64
 13  남녀용 겉옷 및 셔츠 도매업    25 non-null     int64
 14  남녀용 겉옷 및 셔츠 도매업.1  25 non-null     int64
 15  기타주점업              25 non-null     int64
 16  기타주점업.1            25 non-null     int64
 17  일반 교과 학원           25 non-null     int64
 18  일반 교과 학원.1         25 non-null     int64
 19  한식 육류요리 전문점        25 non-null     int64
 20  한식 육류요리 전문점.1      25 non-null     int64
dtypes: int64(20), object(1)
memory usage: 4.2+ KB

,자치구,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,두발미용업,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
0,종로구,215,215,1548,5912,618,646,549,889,261,...,948,3613,400,962,537,1413,110,382,437,1982
1,중구,230,235,1588,6414,300,333,576,1152,339,...,869,3542,10810,24248,381,982,57,175,443,2121
2,용산구,416,523,857,2987,455,466,791,1214,366,...,634,2076,54,317,487,1332,104,573,300,1184
3,성동구,1200,2527,956,2785,1072,1161,801,1453,489,...,547,1859,149,1572,285,621,258,1494,400,1545
4,광진구,1119,1744,963,2861,968,985,871,1313,746,...,590,1887,89,687,633,1577,413,1646,467,1678
5,동대문구,1546,2093,1236,3566,1431,1456,842,1208,611,...,494,1472,211,976,499,1082,302,984,442,1509
6,중랑구,3634,6262,991,2479,1804,1877,738,1104,790,...,381,1037,63,284,535,1000,288,1045,499,1504
7,성북구,1835,2643,973,2822,1312,1335,846,1175,739,...,457,1384,85,454,512,1030,464,1755,365,1334
8,강북구,1713,2589,965,2663,1024,1030,589,867,673,...,358,1095,40,94,580,1275,220,740,362,1176
9,도봉구,2993,5783,672,2009,1571,1574,515,794,600,...,288,837,22,43,258,477,351,1162,302,943
10,노원구,4114,6074,866,2650,1730,1736,714,1053,782,...,535,1748,30,123,355,844,735,3281,428,1557
11,은평구,3108,4430,881,2585,1340,1349,1134,1614,947,...,457,1296,26,74,484,925,551,1793,476,1639
12,서대문구,1747,2677,863,2694,802,808,667,956,598,...,370,1323,22,68,497,1127,361,1268,311,1088
13,마포구,1165,1838,1411,4705,770,829,1149,1903,896,...,1369,4475,96,1209,1011,2559,469,1855,701,2928
14,양천구,2735,4942,831,2800,1286,1293,922,1364,838,...,402,1375,25,52,415,851,1284,5804,281,1111
15,강서구,3735,6922,1325,4584,1799,1862,1311,2352,1015,...,690,2530,78,700,794,1709,672,2347,581,2274
16,구로구,2757,3817,1048,3215,1318,1351,789,1213,729,...,421,1384,114,923,576,1165,336,1111,428,1496
17,금천구,1100,2598,867,2619,935,997,671,1381,488,...,383,1215,200,2575,391,685,153,487,300,1042
18,영등포구,1349,2397,1738,6476,1281,1429,986,1566,673,...,838,3295,76,1220,636,1489,288,1082,494,2151
19,동작구,1033,1115,765,2322,830,844,883,1483,651,...,486,1628,20,199,439,955,407,1463,331,1177
20,관악구,1286,2027,1226,3689,1579,1600,1010,2136,895,...,581,2049,31,190,658,1672,354,1230,422,1628
21,서초구,417,903,1564,6712,386,411,1457,2758,676,...,1012,3897,157,1563,446,1255,812,3812,445,2338
22,강남구,1796,2517,2415,11486,445,487,2337,6508,1241,...,1624,7273,384,8320,713,2528,1426,9020,827,5008
23,송파구,2638,4850,1575,5760,1910,1931,1677,3190,1137,...,975,3372,147,2830,628,1469,876,4160,639,2781
24,강동구,3295,4980,1101,3388,1528,1566,1188,1990,900,...,546,1660,59,1433,589,1349,620,2104,428,1459

In [4]:
a.columns

Index(['자치구', '택시운송업', '택시운송업.1', '한식 일반 음식점업', '한식 일반 음식점업.1', '용달 화물자동차 운송업',
       '용달 화물자동차 운송업.1', '부동산 중개 및 대리업', '부동산 중개 및 대리업.1', '두발미용업', '두발미용업.1',
       '커피전문점', '커피전문점.1', '남녀용 겉옷 및 셔츠 도매업', '남녀용 겉옷 및 셔츠 도매업.1', '기타주점업',
       '기타주점업.1', '일반 교과 학원', '일반 교과 학원.1', '한식 육류요리 전문점', '한식 육류요리 전문점.1'],
      dtype='object')

In [69]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# seoul_business[4:]

In [70]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [5]:
# 해당 데이터프레임을 'df_seoul_business.csv' 파일로 저장하세요.
a.to_csv("df_seoul_business.csv",index=False)

---

# 3.데이터 분석하기
+ KeyPoint : 데이터의 형태를 살펴보고 다양한 분석기법을 통해 모델링에 적합하도록 정제요소를 선별할 수 있다.
  * 데이터들의 패턴 탐색
  * 변수들간의 관계 파악

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# 시각화 한글폰트 설정
# 맑은 고딕

plt.rc('font', family='Malgun Gothic')
sns.set(font="Malgun Gothic",#"NanumGothicCoding", 
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')

# scipy
import scipy.stats as spst

#### [실습문제4] 데이터 분포 알아보기
* 다양한 변수를 기준으로 그래프를 그려보고 인사이트를 도출해보세요.

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [ ]:
# 위 차트를 통해 알게된 사실을 정리해봅시다.
# 1. 
# 2.
# 3.

---